{
 "title": "Visão Geral Internet",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Disponibilidade Router Claro",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Routers" },
     "host": { "filter": "Router Claro" },
     "item": { "filter": "ICMP ping" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Disponibilidade Router Mesh Controller",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Routers" },
     "host": { "filter": "Router Mesh Controller" },
     "item": { "filter": "ICMP ping" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Disponibilidade Router Mesh Client 1",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Routers" },
     "host": { "filter": "Router Mesh Client 1" },
     "item": { "filter": "ICMP ping" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Disponibilidade Internet",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Routers" },
     "host": { "filter": "Router Claro" },
     "item": { "filter": "Status Internet" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Perda Pacotes Router Claro",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 3 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Routers" },
     "host": { "filter": "Router Claro" },
     "item": { "filter": "ICMP loss" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Perda Pacotes Router Mesh Controller",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 3 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Routers" },
     "host": { "filter": "Router Mesh Controller" },
     "item": { "filter": "ICMP loss" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Perda Pacotes Router Mesh Client 1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 3 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Routers" },
     "host": { "filter": "Router Mesh Client 1" },
     "item": { "filter": "ICMP loss" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Perda Pacotes Router Internet",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 3 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Routers" },
     "host": { "filter": "Router Claro" },
     "item": { "filter": "Perdas pacotes Internet" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Latência Router Claro",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 11 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Routers" },
     "host": { "filter": "Router Claro" },
     "item": { "filter": "ICMP response time" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Latência Router Mesh Controller",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 11 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Routers" },
     "host": { "filter": "Router Mesh Controller" },
     "item": { "filter": "ICMP response time" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Latência Router Mesh Client 1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 11 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Routers" },
     "host": { "filter": "Router Mesh Client 1" },
     "item": { "filter": "ICMP response time" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Latência Internet",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 11 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Routers" },
     "host": { "filter": "Router Claro" },
     "item": { "filter": "Latência Internet" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  }
 ]
}